// Code generated by "stringer -type=PacketType"; DO NOT EDIT.

package trelay

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectRequest-1]
	_ = x[Disconnect-2]
	_ = x[SetUserSlot-3]
	_ = x[PlayerInfo-4]
	_ = x[PlayerInventorySlot-5]
	_ = x[RequestWorldData-6]
	_ = x[WorldInfo-7]
	_ = x[GetSectionOrRequestSync-8]
	_ = x[Status-9]
	_ = x[SendSection-10]
	_ = x[SectionTileFrame-11]
	_ = x[SpawnPlayer-12]
	_ = x[UpdatePlayer-13]
	_ = x[PlayerActive-14]
	_ = x[PlayerHP-16]
	_ = x[ModifyTile-17]
	_ = x[Time-18]
	_ = x[DoorToggle-19]
	_ = x[SendTileSquare-20]
	_ = x[UpdateItemDrop-21]
	_ = x[UpdateItemOwner-22]
	_ = x[NPCUpdate-23]
	_ = x[StrikeNPCwithHeldItem-24]
	_ = x[ProjectileUpdate-27]
	_ = x[NPCStrike-28]
	_ = x[DestroyProjectile-29]
	_ = x[TogglePVP-30]
	_ = x[GetChestContentsOrActiveChest-31]
	_ = x[ChestItem-32]
	_ = x[SetChestNameOrOpenChest-33]
	_ = x[PlaceOrKillChest-34]
	_ = x[HealEffect-35]
	_ = x[PlayerZone-36]
	_ = x[RequestPassword-37]
	_ = x[SendPassword-38]
	_ = x[RemoveItemOwner-39]
	_ = x[SetActiveNPC-40]
	_ = x[PlayerItemAnimation-41]
	_ = x[PlayerMana-42]
	_ = x[ManaEffect-43]
	_ = x[KillMe-44]
	_ = x[PlayerTeam-45]
	_ = x[RequestSign-46]
	_ = x[UpdateOrDisplaySign-47]
	_ = x[SetLiquid-48]
	_ = x[CompleteConnectionAndSpawn-49]
	_ = x[UpdatePlayerBuff-50]
	_ = x[SpecialNPCEffect-51]
	_ = x[Unlock-52]
	_ = x[AddNPCBuff-53]
	_ = x[UpdateNPCBuff-54]
	_ = x[AddPlayerBuff-55]
	_ = x[UpdateNPCName-56]
	_ = x[UpdateGoodOrEvil-57]
	_ = x[PlayMusicItem-58]
	_ = x[HitSwitch-59]
	_ = x[NPCHomeUpdate-60]
	_ = x[SpawnBossOrInvasion-61]
	_ = x[PlayerDodge-62]
	_ = x[PaintTile-63]
	_ = x[PaintWall-64]
	_ = x[PlayerOrNPCTeleport-65]
	_ = x[HealOtherPlayer-66]
	_ = x[ClientUUID-68]
	_ = x[GetChestName-69]
	_ = x[CatchNPC_bugs-70]
	_ = x[ReleaseNPC-71]
	_ = x[TravellingMerchantInventory-72]
	_ = x[TeleportationPotion-73]
	_ = x[AnglerQuest-74]
	_ = x[CompleteAnglerquesttoday-75]
	_ = x[NumberOfAnglerQuestsCompleted-76]
	_ = x[CreateTemporaryAnimation-77]
	_ = x[ReportInvasionProgress-78]
	_ = x[PlaceObject-79]
	_ = x[SyncPlayerChestIndex-80]
	_ = x[CreateCombatText-81]
	_ = x[LoadNetModule-82]
	_ = x[SetNPCKillCount-83]
	_ = x[SetPlayerStealth-84]
	_ = x[ForceItemIntoNearestChest-85]
	_ = x[UpdateTileEntity-86]
	_ = x[PlaceTileEntity-87]
	_ = x[AlterItemDrop-88]
	_ = x[PlaceItemFrame-89]
	_ = x[UpdateItemDrop_Instanced-90]
	_ = x[SyncEmoteBubble-91]
	_ = x[SyncExtraValue-92]
	_ = x[SocialHandshake-93]
	_ = x[KillPortal-95]
	_ = x[PlayerTeleportThroughPortal-96]
	_ = x[NotifyPlayerNPCKilled-97]
	_ = x[NotifyPlayerOfEvent-98]
	_ = x[UpdateMinionTarget-99]
	_ = x[NPCTeleportThroughPortal-100]
	_ = x[UpdateShieldStrengths-101]
	_ = x[NebulaLevelUpRequest-102]
	_ = x[UpdateMoonLordCountdown-103]
	_ = x[SetNPCShopItem-104]
	_ = x[ToggleGemLock-105]
	_ = x[PoofofSmoke-106]
	_ = x[SmartChatMessage-107]
	_ = x[WiredCannonShot-108]
	_ = x[MassWireOperation-109]
	_ = x[MassWireOperationConsume-110]
	_ = x[ToggleBirthdayParty-111]
	_ = x[GrowFX-112]
	_ = x[CrystalInvasionStart-113]
	_ = x[CrystalInvasionWipeAll-114]
	_ = x[MinionAttackTargetUpdate-115]
	_ = x[CrystalInvasionSendWaitTime-116]
	_ = x[PlayerHurtV2-117]
	_ = x[PlayerDeathV2-118]
	_ = x[CombatTextString-119]
	_ = x[Emoji-120]
	_ = x[TEDisplayDollItemSync-121]
	_ = x[RequestTileEntityInteraction-122]
	_ = x[WeaponsRackTryPlacing-123]
	_ = x[TEHatRackItemSync-124]
	_ = x[SyncTilePicking-125]
	_ = x[SyncRevengeMarker-126]
	_ = x[RemoveRevengeMarker-127]
	_ = x[LandGolfBallInCup-128]
	_ = x[FinishedConnectingToServer-129]
	_ = x[FishOutNPC-130]
	_ = x[TamperWithNPC-131]
	_ = x[PlayLegacySound-132]
	_ = x[FoodPlatterTryPlacing-133]
	_ = x[UpdatePlayerLuckFactors-134]
	_ = x[DeadPlayer-135]
	_ = x[SyncCavernMonsterType-136]
	_ = x[RequestNPCBuffRemoval-137]
	_ = x[ClientSyncedInventory-138]
	_ = x[SetCountsAsHostForGameplay-139]
	_ = x[SetMiscEventValues-140]
	_ = x[RequestLucyPopup-141]
	_ = x[SyncProjectileTrackers-142]
}

const (
	_PacketType_name_0 = "ConnectRequestDisconnectSetUserSlotPlayerInfoPlayerInventorySlotRequestWorldDataWorldInfoGetSectionOrRequestSyncStatusSendSectionSectionTileFrameSpawnPlayerUpdatePlayerPlayerActive"
	_PacketType_name_1 = "PlayerHPModifyTileTimeDoorToggleSendTileSquareUpdateItemDropUpdateItemOwnerNPCUpdateStrikeNPCwithHeldItem"
	_PacketType_name_2 = "ProjectileUpdateNPCStrikeDestroyProjectileTogglePVPGetChestContentsOrActiveChestChestItemSetChestNameOrOpenChestPlaceOrKillChestHealEffectPlayerZoneRequestPasswordSendPasswordRemoveItemOwnerSetActiveNPCPlayerItemAnimationPlayerManaManaEffectKillMePlayerTeamRequestSignUpdateOrDisplaySignSetLiquidCompleteConnectionAndSpawnUpdatePlayerBuffSpecialNPCEffectUnlockAddNPCBuffUpdateNPCBuffAddPlayerBuffUpdateNPCNameUpdateGoodOrEvilPlayMusicItemHitSwitchNPCHomeUpdateSpawnBossOrInvasionPlayerDodgePaintTilePaintWallPlayerOrNPCTeleportHealOtherPlayer"
	_PacketType_name_3 = "ClientUUIDGetChestNameCatchNPC_bugsReleaseNPCTravellingMerchantInventoryTeleportationPotionAnglerQuestCompleteAnglerquesttodayNumberOfAnglerQuestsCompletedCreateTemporaryAnimationReportInvasionProgressPlaceObjectSyncPlayerChestIndexCreateCombatTextLoadNetModuleSetNPCKillCountSetPlayerStealthForceItemIntoNearestChestUpdateTileEntityPlaceTileEntityAlterItemDropPlaceItemFrameUpdateItemDrop_InstancedSyncEmoteBubbleSyncExtraValueSocialHandshake"
	_PacketType_name_4 = "KillPortalPlayerTeleportThroughPortalNotifyPlayerNPCKilledNotifyPlayerOfEventUpdateMinionTargetNPCTeleportThroughPortalUpdateShieldStrengthsNebulaLevelUpRequestUpdateMoonLordCountdownSetNPCShopItemToggleGemLockPoofofSmokeSmartChatMessageWiredCannonShotMassWireOperationMassWireOperationConsumeToggleBirthdayPartyGrowFXCrystalInvasionStartCrystalInvasionWipeAllMinionAttackTargetUpdateCrystalInvasionSendWaitTimePlayerHurtV2PlayerDeathV2CombatTextStringEmojiTEDisplayDollItemSyncRequestTileEntityInteractionWeaponsRackTryPlacingTEHatRackItemSyncSyncTilePickingSyncRevengeMarkerRemoveRevengeMarkerLandGolfBallInCupFinishedConnectingToServerFishOutNPCTamperWithNPCPlayLegacySoundFoodPlatterTryPlacingUpdatePlayerLuckFactorsDeadPlayerSyncCavernMonsterTypeRequestNPCBuffRemovalClientSyncedInventorySetCountsAsHostForGameplaySetMiscEventValuesRequestLucyPopupSyncProjectileTrackers"
)

var (
	_PacketType_index_0 = [...]uint8{0, 14, 24, 35, 45, 64, 80, 89, 112, 118, 129, 145, 156, 168, 180}
	_PacketType_index_1 = [...]uint8{0, 8, 18, 22, 32, 46, 60, 75, 84, 105}
	_PacketType_index_2 = [...]uint16{0, 16, 25, 42, 51, 80, 89, 112, 128, 138, 148, 163, 175, 190, 202, 221, 231, 241, 247, 257, 268, 287, 296, 322, 338, 354, 360, 370, 383, 396, 409, 425, 438, 447, 460, 479, 490, 499, 508, 527, 542}
	_PacketType_index_3 = [...]uint16{0, 10, 22, 35, 45, 72, 91, 102, 126, 155, 179, 201, 212, 232, 248, 261, 276, 292, 317, 333, 348, 361, 375, 399, 414, 428, 443}
	_PacketType_index_4 = [...]uint16{0, 10, 37, 58, 77, 95, 119, 140, 160, 183, 197, 210, 221, 237, 252, 269, 293, 312, 318, 338, 360, 384, 411, 423, 436, 452, 457, 478, 506, 527, 544, 559, 576, 595, 612, 638, 648, 661, 676, 697, 720, 730, 751, 772, 793, 819, 837, 853, 875}
)

func (i PacketType) String() string {
	switch {
	case 1 <= i && i <= 14:
		i -= 1
		return _PacketType_name_0[_PacketType_index_0[i]:_PacketType_index_0[i+1]]
	case 16 <= i && i <= 24:
		i -= 16
		return _PacketType_name_1[_PacketType_index_1[i]:_PacketType_index_1[i+1]]
	case 27 <= i && i <= 66:
		i -= 27
		return _PacketType_name_2[_PacketType_index_2[i]:_PacketType_index_2[i+1]]
	case 68 <= i && i <= 93:
		i -= 68
		return _PacketType_name_3[_PacketType_index_3[i]:_PacketType_index_3[i+1]]
	case 95 <= i && i <= 142:
		i -= 95
		return _PacketType_name_4[_PacketType_index_4[i]:_PacketType_index_4[i+1]]
	default:
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
